variable "component" {}
variable "env" {}
variable "engine" {}
variable "engine_version" {}
variable "tags" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "sg_subnet_cidr" {}
variable "kms_key_arn" {}
variable "db_instance_count" {}
variable "instance_class" {}